export enum RouteNamesEnum {
  home = '/',
  dashboard = '/dashboard',
  unlock = '/unlock',
  disclaimer = '/disclaimer',
  mint = '/mint',
  drop = '/drop',
  quiz = '/quiz',
  lotteries = '/lotteries',
  vouchers = '/vouchers',
  collections = '/collections',
  nfts = '/nfts',
  profile = '/profile',
  locker = '/locker',
  claim = '/claim',
  claimid = '/claim/:id',
  claimadmin = '/claimadmin',
  marketplace = '/marketplace',
  marketplaceCollections = '/marketplace/collections',
  marketplaceCollectionDetail = '/marketplace/collections/:id',
  faapu = '/faapu',
  dinogazette = '/dinogazette',
  wallet = '/wallet',
  royalties = '/royalties'
}
